#!/bin/bash

CFG="baseservice.cfg"
[ -f $CFG ] && cp -f $CFG $CFG.`date +%Y%m%d` || :

baseservice_templ () {
echo "###############################################################################"
echo "###############################################################################"
echo "#"
echo "# SERVICE DEFINITIONS"
echo "#"
echo "###############################################################################"
echo "###############################################################################"
echo ""
echo ""
echo "# Define a service to "ping" the local machine"
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             PING"
echo "        check_command                   check_ping!100.0,20%!500.0,60%"
echo "        }"
echo ""
echo ""
echo "# Define a service to check the disk space of the root partition"
echo "# on the local machine.  Warning if < 20% free, critical if"
echo "# < 10% free space on partition."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             Root Partition"
echo "        check_command                   check_local_disk!20%!10%!/"
echo "        }"
echo ""
echo ""
echo ""
echo "# Define a service to check the number of currently logged in"
echo "# users on the local machine.  Warning if > 20 users, critical"
echo "# if > 50 users."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             Current Users"
echo "        check_command                   check_local_users!20!50"
echo "        }"
echo ""
echo ""
echo "# Define a service to check the number of currently running procs"
echo "# on the local machine.  Warning if > 350 processes, critical if"
echo "# > 500 users."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             Total Processes"
echo "        check_command                   check_local_procs!350!500!RSZDT"
echo "        }"
echo ""
echo ""
echo ""
echo "# Define a service to check the load on the local machine."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             Current Load"
echo "        check_command                   check_local_load!5.0,4.0,3.0!10.0,6.0,4.0"
echo "        }"
echo ""
echo ""
echo ""
echo "# Define a service to check the swap usage the local machine."
echo "# Critical if less than 10% of swap is free, warning if less than 20% is free"
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             Swap Usage"
echo "        check_command                   check_local_swap!20!10"
echo "        }"
echo ""
echo ""
echo ""
echo "# Define a service to check SSH on the local machine."
echo "# Disable notifications for this service by default, as not all users may have SSH enabled."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             SSH"
echo "        check_command                   check_ssh"
echo "        notifications_enabled           0"
echo "        }"
echo ""
echo ""
echo ""
echo "# Define a service to check HTTP on the local machine."
echo "# Disable notifications for this service by default, as not all users may have HTTP enabled."
echo ""
echo "define service{"
echo "        use                             local-service         ; Name of service template to use"
echo "        host_name                       $HOSTLIST"
echo "        service_description             HTTP"
echo "        check_command                   check_http"
echo "        notifications_enabled           0"
echo "        }"
echo ""
}

add_host_list () {
while read HOST IP
do
  echo -n "$HOST,"
done < host.list
echo localhost
}

main (){
HOSTLIST=$(add_host_list)
baseservice_templ
}

main > $CFG
